version: '3.4'

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 1433:1433
    environment:
        SA_PASSWORD: 'tester@123'
        ACCEPT_EULA: 'Y'

  merchantservice:
    image: ${DOCKER_REGISTRY-}merchantservice
    build:
      context: .
      dockerfile: MerchantService/Dockerfile

  model:
    image: ${DOCKER_REGISTRY-}model
    build:
      context: .
      dockerfile: Models/Dockerfile


  transactionservice:
    image: ${DOCKER_REGISTRY-}transactionservice
    build:
      context: .
      dockerfile: TransactionService/Dockerfile


  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
